commands/root.go
internal/config.go

change default config path from "~/.hzc.yaml" to ".local/share/hz-cli/.hzc.yaml"

change default config file path

---

README.md
internal/cobraprompt/prompt.go

Implements shortcuts to jump words on prompt. Documents already existing shortcuts on Readme

Control Left-Right Arrow Shortcuts [API-1208]

---

sqlcmd/root.go

fix sql example

---

.github/workflows/build_release.yml
.goreleaser.yml
Makefile
go.mod
go.sum
internal/browser/browser.go
internal/browser/sql.go
internal/connect.go
sqlcmd/query.go
sqlcmd/root.go

- Changed go client version to leverage from the latest developments with versioning via build flags
- Modified makefile and goreleaser to build with client type name and version

Phone home support [API-1355]

---

README.md
internal/conversion.go
types/mapcmd/get-all.go
types/mapcmd/get.go
types/mapcmd/put-all.go
types/mapcmd/put.go
types/mapcmd/remove.go
types/mapcmd/use.go

Some examples may be lengthy for command line interface (small window size)

Simplify examples

---

.gitignore
Makefile

Updated makefile

---

clustercmd/cluster.go

copy loop var to fix bug

---

internal/connect.go

Added check mechanism to prevent multiple client creation on interactive mode.

Multiple client creation [API-1383]

---

.github/workflows/jira.yml

This adds the pipeline for adding issues to the Jira.
<strike>
@yuce Can you please edit the secrets of the repo for the following keys?
```
JIRA_BASE_URL
JIRA_USER_EMAIL
JIRA_API_TOKEN
```
</strike>
Nvm, thanks!

Add to-jira label pipeline [API-1454]

---

internal/connect.go
sqlcmd/root.go

fixes #85 
There is also a bug #99  this does not address it

Fix connection bug to non-existing members on SQL screen [API-1466]

---

.github/workflows/jira.yml

Fix mismatched values [API-1454]

---

config/config.go
config/config_test.go

Refactors the default config file that the user interacts with.

Refactor Default Config [API-1376]

---

internal/browser/browser.go
internal/browser/seperator.go

Adds a widget to SQL browser to indicate the progress on a query

Query progress widget [API-1445]

---

.goreleaser.yml
internal/format/format.go
internal/format/format_test.go
internal/termdbms/viewer/util.go
sqlcmd/query.go
sqlcmd/root.go
sqlcmd/sql_test.go

Adds SQL formatting for dates fixes #128

Add time related type formatting to SQL command and browser [API-1515]

---

config/config.go
config/config_test.go
config/logger.go
config/logger_test.go
main.go
rootcmd/root.go
run.go

Adds a flag to specify log level for go client.
Adds utility to direct logs to a file.

Add utility to direct logging to a file [API-1543]

---

internal/cobraprompt/prompt.go
main.go
rootcmd/root.go
rootcmd/root_test.go
types/mapcmd/destroy.go
types/mapcmd/entries.go
types/mapcmd/flagdecs.go
types/mapcmd/force-unlock.go
types/mapcmd/keys.go
types/mapcmd/lock.go
types/mapcmd/map.go
types/mapcmd/map_it_test.go
types/mapcmd/remove-many.go
types/mapcmd/set.go
types/mapcmd/size.go
types/mapcmd/trylock.go
types/mapcmd/unlock.go
types/mapcmd/values.go

This work adds the following map commands to CLC
- remove many
- keys
- values
- entries
- size
- destroy
- lock
- tryLock
- unLock (only for interactive mode)
- set
Also with the addition of "set" command, the put command now prints the older value of the corresponding key

Additions to map commands [API-1540]

---

docs/antora-playbook.yml
docs/modules/ROOT/nav.adoc

- nav.adoc - Fixes two broken links and removes a redundant link
- antora-playbook.yml - Adds netlify url

DOCS-306 Fix broken entries in nav and adds netlify url

---

docs/antora-playbook-local.yml
docs/antora-playbook.yml

Remove redundant space in antora playbooks.

DOCS-306 Remove space before UI Bundle URL

---

.github/workflows/validate-docs.yml
docs/check-links-playbook.yml

Exclude V/5.2 rn
Update node version

DOCS-318 Fix link checker

---

docs/check-links-playbook.yml

Reverting earlier change to build version exclusion.

DOCS-318 Remove invalid version exclusion

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/release-notes.adoc

DOCS-330 Release Notes

---

docs/antora.yml

Add the following line to antora.yml.
start_page: overview.adoc

DOCS-310 add start_page attribute to anotora.yml

---

docs/modules/ROOT/pages/overview.adoc

DOCS-362 Content Error

---

docs/antora.yml

Fix url sent to Algolia search to agree with search tag

DOCS-388_Fix_release_details_sent_to_search

---

docs/modules/ROOT/pages/install-clc.adoc

Add final install steps for Linux, Mac, and Windows

DOCS-412 CLC Install Updates

---

go.mod
go.sum

Updated go.mod to use Go client at master

Updated go.mod

---

base/commands/config/config_list.go
base/commands/map/map_entry_set.go
base/commands/map/map_it_test.go
base/commands/shell.go
base/commands/sql/common.go
base/commands/sql/sql.go
base/commands/sql/sql_it_test.go
go.mod
go.sum
internal/it/test_context.go

* More consistent success messages when a list doesn't have any items.
* Fixed a race in shell command.
* Fixed SQL querying
* Various test fixes

Various Improvements

---

docs/antora.yml

Updates antora.yml for v/5.3.z

DOCS-521 CLC Version Update

---

.github/workflows/nightly_tests.yaml
base/commands/viridian/common.go
base/commands/viridian/custom_class_it_test.go
base/commands/viridian/download_logs.go
base/commands/viridian/download_logs_it_test.go
base/commands/viridian/viridian_cluster_create.go
base/commands/viridian/viridian_it_test.go
clc/config/import.go
docs/antora.yml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/clc-job.adoc
docs/modules/ROOT/pages/clc-viridian.adoc
docs/modules/ROOT/pages/release-notes-5.3.0-BETA-2.adoc
internal/it/test_context.go
internal/viridian/api.go
internal/viridian/cluster_log.go

Waits for the cluster creation and creates a configuration from the cluster.

Viridian update

---

base/commands/sql/sql_it_test.go
base/initializers.go
base/printers.go
clc/const.go
internal/it/test_context.go
internal/output/utils.go
internal/table/table.go
internal/table/table_test.go

* Updated table to have multiline rows.
* Non-stream tables observe `CLC_MAX_COLS` environment variable.
* Other refactoring.

[CLC-67] Updated table printer

---

README.md
base/commands/viridian/common.go
base/commands/viridian/viridian_cluster_get.go
base/commands/viridian/viridian_cluster_list.go
clc/cmd/exec_context.go
docs/modules/ROOT/pages/install-clc.adoc

- Use pause consistently
- Updated doc for MacOS
- Do not print an error message on user cancelled

Various Updates

---

docs/modules/ROOT/pages/jet-job-management.adoc

Update main in line with changes made to 5.3.

DOCS-504 Update Jet Job tutorial

---

Makefile
extras/windows/installer/hazelcast-clc-installer.iss

* Set default CLC version to `v0.0.0-CUSTOMBUILD`
* Include `dessert.sql` in the release packages
* Set windows installer version using an environment variable.

Packaging improvements

---

base/commands/viridian/viridian_cluster_get.go

Reorganized the columns in the result of `viridian get-cluster`.

Reorganize viridian get-cluster command

---

docs/modules/ROOT/pages/config-wizard.adoc
docs/modules/ROOT/pages/managing-viridian-clusters.adoc

- Updates to style, formatting and language of tutorial
- Changes will need to be backported to 5.3.1

DOCS-544 Refactor Manage Viridian Clusters Tutorial

---

docs/antora.yml

Updated version due to build failure

DOCS-544 Version update

---

docs/antora.yml
docs/modules/ROOT/pages/managing-viridian-clusters.adoc

- Update minor release version (5.3.1). Reflects latest minor release.
- Correct heading on tutorial

DOCS-546 Update minor release version

---

docs/modules/ROOT/pages/managing-viridian-clusters.adoc

Update tutorial heading (H1 rather than H2)

DOCS-544 Correct tutorial heading

---

base/commands/map/map_it_test.go
base/commands/map/map_lock.go
base/commands/map/map_try_lock.go
base/commands/map/map_unlock.go
base/commands/map/map_values.go
clc/cmd/clc.go
docs/modules/ROOT/pages/clc-map.adoc
internal/plug/registry.go
internal/proto/codec/map_values_codec.go

Added following commands:
- map lock
- map try-lock
- map unlock
- map values

Add missing map commands [CLC-200]

---

base/commands/viridian/viridian_cluster_stop.go
base/commands/viridian/viridian_it_test.go
clc/secrets/secrets.go
docs/modules/ROOT/pages/clc-viridian.adoc
docs/modules/ROOT/pages/managing-viridian-clusters.adoc

- Renamed `viridian pause-cluster` to `viridian stop-cluster`.
- Simplified secret reading/writing

Viridian command updates

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/clc-home.adoc
docs/modules/ROOT/pages/config-wizard.adoc
docs/modules/ROOT/pages/configuration.adoc
docs/modules/ROOT/pages/install-clc.adoc
docs/modules/ROOT/pages/overview.adoc
docs/modules/ROOT/pages/release-notes.adoc
docs/modules/ROOT/pages/upgrade-clc.adoc

As per previous PR. Temporarily remove references to Viridian.

DOCS-571 Remove CLC and Viridian References

---

README.md
base/commands/config/config_import.go
base/commands/config/config_it_test.go
clc/config/import.go
docs/modules/ROOT/pages/clc-config.adoc
internal/types/types.go
internal/viridian/api.go
internal/viridian/cluster_log.go

- Use Python code sample instead of Go
- Fixed a couple of issues

Use Python code sample instead of Go

---

README.md
docs/antora-playbook-local.yml
docs/antora-playbook.yml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/clc-config.adoc
docs/modules/ROOT/pages/clc-home.adoc
docs/modules/ROOT/pages/config-wizard.adoc
docs/modules/ROOT/pages/configuration.adoc
docs/modules/ROOT/pages/connect-to-viridian.adoc
docs/modules/ROOT/pages/get-started.adoc
docs/modules/ROOT/pages/overview.adoc
docs/modules/ROOT/pages/release-notes.adoc

Updates for reintroducing Viridian content to 5.2.z.

Docs 608 Reintroduce Viridian content

---

README.md
docs/antora-playbook-local.yml
docs/antora-playbook.yml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/clc-commands.adoc
docs/modules/ROOT/pages/clc-config.adoc
docs/modules/ROOT/pages/clc-home.adoc
docs/modules/ROOT/pages/clc-job.adoc
docs/modules/ROOT/pages/clc-viridian.adoc
docs/modules/ROOT/pages/config-wizard.adoc
docs/modules/ROOT/pages/configuration.adoc
docs/modules/ROOT/pages/connect-to-viridian.adoc
docs/modules/ROOT/pages/environment-variables.adoc
docs/modules/ROOT/pages/get-started.adoc
docs/modules/ROOT/pages/jet-job-management.adoc
docs/modules/ROOT/pages/managing-viridian-clusters.adoc
docs/modules/ROOT/pages/overview.adoc
docs/modules/ROOT/pages/release-notes-5.2.0.adoc
docs/modules/ROOT/pages/release-notes-5.3.0-BETA-1.adoc
docs/modules/ROOT/pages/release-notes-5.3.0-BETA-2.adoc
docs/modules/ROOT/pages/release-notes-5.3.0.adoc
docs/modules/ROOT/pages/release-notes-5.3.1.adoc

Changes already approved for `main`. This PR adds the same changes to 5.3.x

DOCS-608 Reintroduce Viridian content

---

base/commands/project/file.go
base/commands/project/project_create_it_test.go
base/commands/viridian/common.go
base/commands/viridian/const.go
base/commands/viridian/viridian_cluster_get.go
base/commands/viridian/viridian_it_test.go
base/commands/viridian/viridian_login.go
clc/config/config.go
clc/config/config_test.go
clc/config/import.go
clc/const.go
clc/paths/paths.go
clc/secrets/secrets.go
go.mod
go.sum
internal/it/test_context.go
internal/viridian/api.go
internal/viridian/cluster.go
internal/viridian/cluster_log.go
internal/viridian/custom_class_download.go
internal/viridian/custom_class_upload.go
internal/viridian/login.go

* Adds the `cluster.api-base` config item to set the the base API URL
* Adds `--api-base` flag to `viridian create-cluster` command
* Saves the API base URL in the Viridian secrets
* Some refactoring

API Base URL config

---

README.md
base/commands/shell.go
docs/modules/ROOT/pages/clc-sql.adoc
docs/modules/ROOT/pages/clc.adoc
docs/modules/ROOT/pages/config-wizard.adoc
docs/modules/ROOT/pages/get-started.adoc
docs/modules/ROOT/pages/overview.adoc

Trivial update to the prompt

---

base/commands/viridian/common.go
base/commands/viridian/viridian_cluster_create.go
base/commands/viridian/viridian_import_config.go
clc/config/config.go
clc/config/import.go
clc/paths/paths.go
clc/paths/paths_test.go
internal/types/types.go
internal/types/types_test.go
internal/viridian/api.go
internal/viridian/cluster.go

* Fixes error checking in config import
* Imports Java and .Net client certificates
* Refactors some config import code
* Increases the number of clusters requested in the cluster list
* Adds `types.Set`

Viridian Updates

---

rc.sh

Port of the resolution to the issue described in https://github.com/hazelcast/hazelcast-cpp-client/pull/1206

Update dependency:get command to latest syntax

---

docs/check-links-playbook.yml
docs/modules/ROOT/pages/clc-job.adoc
docs/modules/ROOT/pages/clc-multimap.adoc
docs/modules/ROOT/pages/clc-project.adoc
docs/modules/ROOT/pages/clc-queue.adoc
docs/modules/ROOT/pages/clc-set.adoc
docs/modules/ROOT/pages/clc-snapshot.adoc
docs/modules/ROOT/pages/clc-topic.adoc
docs/modules/ROOT/pages/clc-viridian.adoc
docs/modules/ROOT/pages/connect-to-viridian.adoc
docs/modules/ROOT/pages/environment-variables.adoc
docs/modules/ROOT/pages/get-started.adoc
docs/modules/ROOT/pages/install-clc.adoc
docs/modules/ROOT/pages/jet-job-management.adoc
docs/modules/ROOT/pages/managing-viridian-clusters.adoc
docs/modules/ROOT/pages/overview.adoc
docs/modules/ROOT/pages/release-notes-5.2.0.adoc
docs/modules/ROOT/pages/release-notes-5.2.1.adoc
docs/modules/ROOT/pages/release-notes-5.3.0-BETA-1.adoc
docs/modules/ROOT/pages/release-notes-5.3.0-BETA-2.adoc
docs/modules/ROOT/pages/release-notes-5.3.0.adoc
docs/modules/ROOT/pages/release-notes-5.3.1.adoc

Minor text updates for consistent use Viridian Cloud as new product name for Hazelcast Viridian.

DOCS-568 Text Changes for consistent renaming to Viridian Cloud

---

docs/check-links-playbook.yml
docs/modules/ROOT/pages/clc-job.adoc
docs/modules/ROOT/pages/clc-multimap.adoc
docs/modules/ROOT/pages/clc-project.adoc
docs/modules/ROOT/pages/clc-queue.adoc
docs/modules/ROOT/pages/clc-set.adoc
docs/modules/ROOT/pages/clc-snapshot.adoc
docs/modules/ROOT/pages/clc-topic.adoc
docs/modules/ROOT/pages/clc-viridian.adoc
docs/modules/ROOT/pages/connect-to-viridian.adoc
docs/modules/ROOT/pages/environment-variables.adoc
docs/modules/ROOT/pages/get-started.adoc
docs/modules/ROOT/pages/install-clc.adoc
docs/modules/ROOT/pages/jet-job-management.adoc
docs/modules/ROOT/pages/managing-viridian-clusters.adoc
docs/modules/ROOT/pages/overview.adoc
docs/modules/ROOT/pages/release-notes-5.2.0.adoc
docs/modules/ROOT/pages/release-notes-5.2.1.adoc
docs/modules/ROOT/pages/release-notes-5.3.0-BETA-1.adoc
docs/modules/ROOT/pages/release-notes-5.3.0-BETA-2.adoc
docs/modules/ROOT/pages/release-notes-5.3.0.adoc
docs/modules/ROOT/pages/release-notes-5.3.1.adoc

Minor text updates for consistent use Viridian Cloud as new product name for Hazelcast Viridian.

DOCS-568 Text changes for consistent renaming to Viridian Cloud v3

---

base/commands/project/project_create_it_test.go
clc/paths/paths.go

* Added `paths.CopyDir` function
* Refactored `project create` test

Refactored project create test

---

docs/modules/ROOT/pages/install-clc.adoc

On investigation, it was decided to introduce conditional text, and only document build from source for pre-release SNAPSHOT CLC

DOCS-632 Requested link update

---

extras/unix/install.sh

* Improves how the updated PATH is recognized.
* Updates also the `.profile` to add `clc` to the `$PATH`.

Adds TMUX support to the install script

---

base/commands/config/config_list.go
base/commands/demo/demo_generate_data.go
base/commands/job/common.go
base/commands/map_common.go
base/commands/sql/testdata/sql_help.txt
base/commands/viridian/viridian_cluster_delete.go
clc/cmd/clc.go
clc/config/wizard/list.go
clc/config/wizard_provider.go
clc/shell/common.go
clc/ux/stage/stage.go
clc/ux/stage/stage_test.go
docs/modules/ROOT/pages/clc-project.adoc

* Fixes some typos
* Changes `ec.ClientInternal` to `cmd.ClientInternal` in some commands.
* Adds the ability to set stage text during execution

Small fixes

---

README.md
base/commands/common.go
base/commands/demo/demo_generate_data.go
base/commands/demo/demo_it_test.go
base/commands/shell.go
clc/const.go
docs/modules/ROOT/pages/clc-demo.adoc
docs/modules/ROOT/pages/install-clc.adoc

* Requires confirmation from the user for `demo generte-data` command.
* Adds "SQL" to the prompt.
* Updates the docs with the new install script link.

[CLC-361] [CLC-341] [CLC-338] Small improvements
