hazelcast/hazelcast-commandline-client

commands/root.go
commands/types/map/map.go

- change shorthand flag for map name from "-m" to "-n"
- remove shorthand for "--cluster-name" to prevent flag collision

Change map name shorthand flag

---

scripts/install.sh

Currently installation script cannot parse release tag correctly. To reproduce to error and fix, you can try
```
x="https://github.com/hazelcast/hazelcast-commandline-client/releases/tag/v0.1.0-preview.1"
echo ${x##*v}
echo ${x##*tag/v}
```
on bash terminal

[EASY] change ghExtractTag for newer release tags

---

internal/cobraprompt/prompt.go
internal/go-prompt/document.go
internal/go-prompt/document_test.go

We observed that ctrl - left did not work as expected. This work tries to fix that. I confirmed that it looks good on:
- zsh with some tweaks to send correct char sequences for ctrl+arrow keys. By default it does not use readline() under the hood. This fix is necessary to capture those.
Dear reviewers, if you have an environment other than this, please also try and see if it is fixed. Thanks!

Fix Ctrl-left behavior [API-1208]

---

internal/conversion.go
types/mapcmd/map.go
types/mapcmd/mapget.go
types/mapcmd/mapput.go

Introduce basic primitive types for serialization for map keys and values for types
Integers (8, 16, 32, 64)
Boolean
Floats (32, 64)

Subset of primitive types support for serialization [API-1179]

---

docs/antora-playbook.yml

This duplicate is breaking the build of the docs staging site.

Fix duplicate key

---

.goreleaser.yml
Makefile
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/clc-commands.adoc
docs/modules/ROOT/pages/hzc-version.adoc
internal/connect.go
rootcmd/root.go
versioncmd/version.go

CLC prints followings when `version` command called:
- Command Line Client Version
- Latest Git commit hash
- Hazelcast Go Client Version
- Go Version
The CLC version is hard coded inside the `internal` package, similar to Go Client. Others are aimed to change dynamically at build and runtime. Since we created a new command, a new folder (`versioncmd`) has been created to accomplish `subCommand` pattern.

version sub-command added. [API-1456]

---

clustercmd/cluster.go
errors/error.go
internal/cobraprompt/prompt.go
main.go
rootcmd/root.go
run.go
runner/run.go
types/mapcmd/clear.go
types/mapcmd/get-all.go
types/mapcmd/get.go
types/mapcmd/map.go
types/mapcmd/put-all.go
types/mapcmd/put.go
types/mapcmd/remove.go
types/mapcmd/use.go

Fix flag validation for interactive mode (turns out it works ok for non-interactive)
Also apart from that, CLC-related errors were being logged instead of "being printed to stderr". This PR fixes that.

Fix Flag Validation for Interactive Mode [API-1563]

---

config/config.go
connwizardcmd/connection.go
internal/cobraprompt/prompt.go
internal/file/file.go
rootcmd/root.go
runner/run.go

It has been discussed to follow the convention below for Windows paths:
Executable: `AppData/Local/Programs/Hazelcast CLC`
Config and "roamable" files: `AppData/Roaming/Hazelcast CLC`
Local data such as logs and command history: `AppData/Local/Hazelcast CLC`

Update paths for Windows[API-1542]

---

clc/cmd/clc.go
clc/cmd/command_context.go

This PR fixes prefixing backslash to commands in the shell by prefixing them only if they are a top level command.

[EASY] Fix CLC commands in the shell

---

docs/antora.yml
docs/modules/ROOT/pages/release-notes.adoc

- Docs version updated to match search tag for algolia search
- Displayed version numbers made consistent. Now all are upper-case

DOCS-380 Update version for Algolia search

---

base/commands/map/map.go
base/commands/map/map_size.go

Fixes: #186 
Blocking call of `map` was saving the created proxy object and returning it in the subsequent commands directly without creating a new proxy. This behaviour results in constant map proxy even if a different map name is specified. 
A new check is added to return if the saved proxy's name matches with the requested map name.

Map name parameter gets stuck to a value in the shell mode [API-1934]

---

clc/config/config.go
clc/config/config_test.go

Labels are displayed in the MC client console for identifying clients.
This PR resolves the ticket but I can implement a `GetStringList()` method for `ReadOnlyProperties` to read labels from config files and assign it to Hazelcast client configuration. Wdyt @yuce, is this change enough?

Add CLC label to client properties for MC.

---

base/commands/viridian/const.go
base/commands/viridian/custom_class_it_test.go
base/commands/viridian/download_logs.go
base/commands/viridian/download_logs_it_test.go
base/commands/viridian/viridian_cluster_create.go
base/commands/viridian/viridian_cluster_delete.go
base/commands/viridian/viridian_cluster_get.go
base/commands/viridian/viridian_cluster_list.go
base/commands/viridian/viridian_cluster_resume.go
base/commands/viridian/viridian_cluster_stop.go
base/commands/viridian/viridian_it_test.go
docs/modules/ROOT/pages/clc-viridian.adoc
go.mod
go.sum
internal/it/test_cluster.go
internal/it/test_context.go
internal/viridian/api.go
internal/viridian/cluster.go
internal/viridian/cluster_log.go
internal/viridian/types.go

Following commands are added to `viridian`
- create-cluster
- delete-cluster
- stop-cluster
- resume-cluster
- get-cluster
- download-logs

Add cluster management commands [CLC-163]

---

base/commands/viridian/common.go
base/commands/viridian/const.go
base/commands/viridian/custom_class_delete.go
base/commands/viridian/custom_class_download.go
base/commands/viridian/custom_class_list.go
base/commands/viridian/custom_class_upload.go
base/commands/viridian/download_logs.go
base/commands/viridian/viridian_cluster_create.go
base/commands/viridian/viridian_cluster_delete.go
base/commands/viridian/viridian_cluster_get.go
base/commands/viridian/viridian_cluster_list.go
base/commands/viridian/viridian_cluster_resume.go
base/commands/viridian/viridian_cluster_stop.go
base/commands/viridian/viridian_cluster_types.go
base/commands/viridian/viridian_import_config.go
base/commands/viridian/viridian_it_test.go
base/commands/viridian/viridian_login.go
docs/modules/ROOT/pages/clc-viridian.adoc
docs/modules/ROOT/pages/managing-viridian-clusters.adoc
errors/error.go
internal/viridian/api.go
internal/viridian/cluster.go
internal/viridian/cluster_log.go
internal/viridian/custom_class_download.go
internal/viridian/custom_class_upload.go
internal/viridian/errors.go
internal/viridian/types.go

- Remove the `--development` flag.
- Rename `--plan` flag of `viridian create-cluster` to `cluster-type` and do not limit the choice to `SERVERLESS`.(The default is `DEVMODE`).
- Add  `viridian list-cluster-types` command.
- Add `viridian import-config` command which imports the cluster configuration from a Viridian cluster.
- Rename `stop-cluster` to `pause-cluster`.
- Revamp the Viridian errors:
-  Log the full Viridian error, but do not display JSON in the user error message.
- Do not display “did you login” except there’s an authentication issue.
- Add `--yes` flag to `viridian delete-custom-class`

[CLC-170] Viridian Command Updates

---

docs/modules/ROOT/pages/jet-job-management.adoc

Some updates to tutorial, including:
- Changes to step 4 to make it easier to use the example Jet job
- Added steps to stop looping statements
**Issues/errors**
- `clc -c dev job submit build/libs/simple-streaming-pipeline-1.0-SNAPSHOT-all.jar –wait` gave the following error `Error: --wait requires the --name to be set`. When I removed `--wait`, the command ran. For now, I have left the command as is.
- `while true; do clc -c dev map size -n my-map; sleep 3; done` does not run for Windows users. I created a small batch file and ran it. Do you want to provide this alternative for Windows users?
```
@echo off
:start
clc -c dev map size -n my-map
timeout 5
goto start
```
- `clc -c dev job cancel prime-job` gave the following error `Error: invalid job ID`.  As a workaround, I suspended the …

DOCS-504 Updates to Jet Job Tutorial

---

base/commands/job/common.go
base/commands/job/const.go
base/commands/job/job_export_snapshot.go
base/commands/job/job_list.go
base/commands/job/job_resume.go
base/commands/job/job_submit.go
base/commands/job/job_terminate.go
base/commands/job/job_test.go
internal/cluster/cluster.go
internal/jet/errors.go
internal/jet/jet_test.go
internal/jet/job.go
internal/jet/util.go

* We will need to use Jet functionality outside of `jet` command, so moved core Jet code to a separate package.
* Added support for submitting the job from a reader.

[CLC-188] Refactor Jet Support

---

base/commands/job/job_submit.go
internal/jet/job.go

* See: https://hazelcast.atlassian.net/browse/HZ-2492
* Also sets the default retries to `0`.

[CLC-194] Workaround for incorrect hash stringify in Hz 5.3.0

---

base/initializers.go
clc/cmd/clc.go
clc/cmd/exec_context.go
clc/cmd/utils.go
clc/const.go
cmd/clc/main.go
docs/modules/ROOT/partials/global-parameters.adoc
errors/error.go

The duration is a string in the form of `AMOUNTunit` where `AMOUNT` is an `integer`, and `unit` is one of the following:
- `ms: milliseconds`
- `s: seconds`
- `m: minutes`
- `h: hours`
Underscore (_) character is ignored in the `AMOUNT`. `unit` is optional and defaults to `ms` if not specified.
The following are a few of the valid DURATIONs:
- `5: 5 seconds`
- `5s: 5 seconds`
- `10000ms: 10000 milliseconds`
- `10_000_000ms: 10000000 milliseconds`

[CLC-187]: Add Global `--timeout` Flag

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/clc-home.adoc
docs/modules/ROOT/pages/clc-job.adoc
docs/modules/ROOT/pages/config-wizard.adoc
docs/modules/ROOT/pages/configuration.adoc
docs/modules/ROOT/pages/environment-variables.adoc
docs/modules/ROOT/pages/overview.adoc
docs/modules/ROOT/pages/release-notes-5.2.0.adoc
docs/modules/ROOT/pages/release-notes-5.3.0-BETA-1.adoc
docs/modules/ROOT/pages/release-notes-5.3.0-BETA-2.adoc
docs/modules/ROOT/pages/release-notes-5.3.0.adoc
docs/modules/ROOT/pages/release-notes-5.3.1.adoc
docs/modules/ROOT/pages/upgrade-clc.adoc

Content is hidden rather than removed (checked with Finn). If all change are correct, I will apply to other branches.

DOCS-571 Remove CLC and Viridian References

---

base/commands/project/project_create_it_test.go
base/commands/project/testdata/simple-streaming-pipeline/Makefile
base/commands/project/testdata/simple-streaming-pipeline/README.md
base/commands/project/testdata/simple-streaming-pipeline/build.gradle
base/commands/project/testdata/simple-streaming-pipeline/settings.gradle
base/commands/project/testdata/simple-streaming-pipeline/src/main/java/com/example/SimplePipeline.java
base/commands/sql/common.go

- Use `testdata` instead of `examples/platform`.
- Copy templates to the temporary `CLC_HOME` dir.
- Remove unnecessary file `base/commands/sql/common.go`.

Fix Project Creator Tests

---

clc/paths/paths.go

Previously any filename with a dot in it was recognized as full path to the configuration.
This PR changes that and only files with `.yaml` extension are recognized as config files.

Ensure config files have the .yaml extension

---

base/commands/viridian/common.go
base/commands/viridian/common_test.go
clc/secrets/secrets.go

Fixes getting the access token path when `--api-key` or `CLC_VIRIDIAN_API_KEY` is used

Fix loading access token when the API key is given explicitly

---

README.md
docs/antora-playbook-local.yml
docs/antora-playbook.yml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/clc-commands.adoc
docs/modules/ROOT/pages/clc-config.adoc
docs/modules/ROOT/pages/clc-home.adoc
docs/modules/ROOT/pages/clc-job.adoc
docs/modules/ROOT/pages/clc-viridian.adoc
docs/modules/ROOT/pages/config-wizard.adoc
docs/modules/ROOT/pages/configuration.adoc
docs/modules/ROOT/pages/connect-to-viridian.adoc
docs/modules/ROOT/pages/environment-variables.adoc
docs/modules/ROOT/pages/get-started.adoc
docs/modules/ROOT/pages/jet-job-management.adoc
docs/modules/ROOT/pages/managing-viridian-clusters.adoc
docs/modules/ROOT/pages/overview.adoc
docs/modules/ROOT/pages/release-notes-5.2.0.adoc
docs/modules/ROOT/pages/release-notes-5.3.0-BETA-1.adoc
docs/modules/ROOT/pages/release-notes-5.3.0-BETA-2.adoc
docs/modules/ROOT/pages/release-notes-5.3.0.adoc
docs/modules/ROOT/pages/release-notes-5.3.1.adoc

Reintroduces hidden Viridian content and updates product name to Viridian Cloud in line with new branding. Once this PR is approved I can update previous versions 5.3.x and 5.2.x with the same changes.
**Outstanding question:**
On both the configuration page (configuration.adoc) and in Get Started (get-started.adoc) we mention downloading the sample Go client to discover a Viridian cloud cluster. Not sure if an alternative to this has been planned.

DOCS-608 Reintroduce Viridian Content and Update Product Name

---

docs/check-links-playbook.yml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/clc-config.adoc
docs/modules/ROOT/pages/connect-to-viridian.adoc
docs/modules/ROOT/pages/get-started.adoc
docs/modules/ROOT/pages/install-clc.adoc
docs/modules/ROOT/pages/overview.adoc
docs/modules/ROOT/pages/release-notes.adoc

Minor text updates for consistent use Viridian Cloud as new product name for Hazelcast Viridian.

DOCS-568 Text changes for consistent renaming to Viridian Cloud v2

---

Makefile

Disabled the verbose test output in order to see the actual test errors easier.

Disabled verbose test output

---

clc/config/wizard/input.go

The banner was showing configuration steps using Go client.
We removed Go client from Viridian, so it should point to CLI.

Fix configuration wizard banner message.

---

README.md
clc/config/config_it_test.go
clc/config/file_provider.go
clc/config/wizard_provider.go
docs/modules/ROOT/pages/configuration.adoc

* If there's a single config and no config was specified, use that as the default config.
* Removes the config wizard import.

[CLC-340] Single config is the default config

---

base/commands/migration/migration_stages.go
base/commands/migration/start_stages.go

- The reason of the problem is that we forgot to handle context errors in for loop while waiting migration to be in progress, so even if we have a timeout error it waits for it to be in progress forever.
- Also this PR increases the timeout of the context, because it was 30 seconds which is same with the backend. So sometimes it used to fail with timeout, sometimes with `Unable to connect to any cluster` error. After increasing the timeout, user will consistently see the `Unable to connect to any cluster` error.

[CLC-432]: Fix hanging problem when source and target clusters is not running
